version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-portfolio:latest
    container_name: ms-portfolio
    ports:
      - "8080:80"
    environment:
      # Add your environment variables here if needed
      # VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      # VITE_SUPABASE_KEY: ${VITE_SUPABASE_KEY}
      # VITE_SUPABASE_SCHEMA: ${VITE_SUPABASE_SCHEMA}
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
