[variables]
# Use Node 20 LTS to satisfy vite@7.x engine requirements
NIXPACKS_NODE_VERSION = "20.19.0"
# Node environment set to production
NODE_ENV = "production"
# Directory where Vite outputs static files
NIXPACKS_SPA_OUTPUT_DIR = "dist"

[phases.setup]
# Install Node 20 instead of the default Node 22
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
# Use npm ci for deterministic installs
cmds = ["npm ci"]

[phases.build]
# Run the Vite build script
cmds = ["npm run build"]

[start]
# Serve the built files using caddy, which is included by the default Nixpacks plan
cmd = "exec caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1"
