[variables]
# Use Node 20 LTS to satisfy vite@7.x engine requirements
NIXPACKS_NODE_VERSION = "20.19.0"
# Node environment set to production
NODE_ENV = "production"
# Directory where Vite outputs static files
NIXPACKS_SPA_OUTPUT_DIR = "dist"

[phases.setup]
# Install Node 20 and Caddy web server for serving the SPA
nixPkgs = ["nodejs_20", "npm-9_x", "caddy"]

[phases.install]
# Use npm ci for deterministic installs in production
cmds = ["npm ci"]

[phases.build]
# Run the Vite build script to generate static files
cmds = ["npm run build"]

[start]
# Serve the built files using Caddy with our custom configuration
# The Caddyfile provides proper SPA routing (fallback to index.html)
cmd = "caddy run --config /app/Caddyfile --adapter caddyfile"
